### ISSUE TITLE
No device support directory for iOS version 12.5

### ISSUE THREAD

**Issue by ZhaoXiangXML** [sonos/dinghy#165]
I'm trying to run unit tests on an iPhone 5s with iOS 12.5 and I got this error:

```
No device support directory for iOS version 12.5 in "/Applications/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport". Time for an XCode update?
```

However I can run an empty XCode project.

I tried to:

```bash
sudo cp -r 12.4 12.5
```

This time I got:

```
(lldb) command source -s 1 '/var/folders/09/nf3rmycs22547ccs_5s8tgxm0000gn/T/mobiledevice-rs-lldb.R7Awu0OT49nj/lldb-script'
Traceback (most recent call last):
  File "/var/folders/09/nf3rmycs22547ccs_5s8tgxm0000gn/T/mobiledevice-rs-lldb.R7Awu0OT49nj/helpers.py", line 8, in connect_command
    process = lldb.target.ConnectRemote(lldb.target.GetDebugger().GetListener(), connect_url, None, error)
AttributeError: 'NoneType' object has no attribute 'ConnectRemote'
Traceback (most recent call last):
  File "/var/folders/09/nf3rmycs22547ccs_5s8tgxm0000gn/T/mobiledevice-rs-lldb.R7Awu0OT49nj/helpers.py", line 13, in set_remote_path
    lldb.target.modules[0].SetPlatformFileSpec(lldb.SBFileSpec(device_app))
AttributeError: 'NoneType' object has no attribute 'modules'
Traceback (most recent call last):
  File "/var/folders/09/nf3rmycs22547ccs_5s8tgxm0000gn/T/mobiledevice-rs-lldb.R7Awu0OT49nj/helpers.py", line 19, in start
    proc = lldb.target.Launch(info, error)
AttributeError: 'NoneType' object has no attribute 'Launch'
```

**Comment by ZhaoXiangXML** [comment]
So I noticed the app is built and code signed at `target/dinghy/xxx/Dinghy.app`. I installed and launched it with:

```
ios-deploy --noninteractive --bundle target/dinghy/xxx/Dinghy.app/
```

I got the following error:

```
......
(lldb)     connect
(lldb)     run
success
(lldb)     autoexit

PROCESS_STOPPED
error: invalid thread
```

And I found this in crash logs:

![image](https://user-images.githubusercontent.com/719497/179996494-9ed1e003-a027-457e-a5a4-49631d15b121.png)

**Comment by ZhaoXiangXML** [comment]
```
otool -L target/dinghy/xxx/Dinghy.app/Dinghy 
target/dinghy/xxx/Dinghy.app/Dinghy:
        /System/Library/Frameworks/Security.framework/Security (compatibility version 1.0.0, current version 60158.120.9)
        /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.120.1)
        /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
        /System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1860.0.0)
        /usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
```
